### ISSUE TITLE
Add `bang` command

### ISSUE THREAD

**Issue by gabr1sr** [kodecsz/discord-bot#29]
## Specification
The user executes the command `/bang` when an animal appears.

## TODOs
- [ ] The bot shows a message saying "Nice shot" if the animal has been shot
- [ ] If the person don't shoot in time, the animal will escape
- [ ] If the person shoot when no animal appeared, show a message saying that there is no animal to shoot
